### ISSUE TITLE
Create Logo and color scheme

### ISSUE THREAD

**Issue by joellian** [CodePath-Pod-24/ProductivityApp#3]
- Come up with a logo design to represent our app
- Choose a color scheme that appeals to our target audience

**Comment by sherrss** [comment]
- Picked 5 logo designs to choose from
- Decided on color scheme with 4 main colors

<img width="545" alt="Screen Shot 2022-10-27 at 7 38 50 PM" src="https://user-images.githubusercontent.com/105692203/198417299-0f46a5df-7d2d-432a-9f45-99fe9804a901.png">
<img width="629" alt="Screen Shot 2022-10-27 at 7 39 11 PM" src="https://user-images.githubusercontent.com/105692203/198417332-a8c1ea68-a35f-4728-92a7-44d97ee8be20.png">
