### ISSUE TITLE
Create a timer 

### ISSUE THREAD

**Issue by SaulLopezLucas** [CodePath-Pod-24/ProductivityApp#6]
- Create the timer by either coding it or by looking at a YouTube video tutorial. 
- Create the buttons to adjust the timer duration (or create a timer wheel that gives users more flexibility with selecting a time)
- Create code to make phone vibrate when the user exits out of the app (this is to help them stay focus and not switch a different app that they're not supposed to be on)

**Comment by sherrss** [comment]
- Created a countdown timer with minute intervals
- Added a tab bar controller for the navigation bar
- Added the timer to the home tab screen 

<img width="189" alt="Screen Shot 2022-10-28 at 12 42 46 AM" src="https://user-images.githubusercontent.com/105692203/198504282-7f03d38f-5188-4917-b793-ff38713bac5d.png">
